# NOTE: update this with your service name
service: serverless-nodejs-starter

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-bundle
  - serverless-plugin-warmup
  - serverless-offline

custom:
  bundle:
    caching: false
    logs: true
  warmup:
    prewarm: true
    enabled: true
    concurrency: 1

#package:
#  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
